version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: indirect
    ignore:
      - update-types:
          - version-update:semver-major
          - version-update:semver-minor
    groups:
      gomod-indirect-patches:
        patterns:
          - "*"
        update-types:
          - patch
    open-pull-requests-limit: 5
