services:
  registry:
    image: registry:2
    ports:
      - 8085:5000
  nginx:
    image: nginxinc/nginx-unprivileged:alpine-slim
    volumes:
      - ./build/ephemeral/repository/http:/usr/share/nginx/html:ro
    ports:
      - 8088:8080
