volumes:
  runner-root-cache:
  runner-go-mod-cache:

services:
  runner:
    image: ${RUNNER}
    volumes:
      - .:/workspace
      - ./build/ephemeral/templates:/templates
      - nginx-content:/repository/http
      - runner-root-cache:/root/.cache
      - runner-go-mod-cache:/go/pkg/mod
    working_dir: /workspace
# --- test tools ---
  editorconfig:
    image: mstruebing/editorconfig-checker
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
  hadolint:
    image: hadolint/hadolint
    entrypoint: /bin/hadolint
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
  checkmake:
    image: mrtazz/checkmake
    volumes:
      - ./Makefile:/Makefile:ro
      - ./make.d:/make.d:ro
