apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.gateway.solo.io.v2
  annotations:
    "helm.sh/hook": crd-install
  labels:
    installationId: r4RQ4m7rfKF0By9jh1zS
spec:
  group: gateway.solo.io.v2
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    shortNames:
      - gw
    singular: gateway
  scope: Namespaced
  version: v2
  versions:
    - name: v2
      storage: true
      served: true
