apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicesscanresults.kubescape.io
spec:
  group: kubescape.io
  names:
    kind: ServiceScanResult
    plural: servicesscanresults
    shortNames:
    - kssa
    singular: servicescanresult
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              clusterIP:
                type: string             
              ports:
                type: array
                items:
                  type: object
                  properties:
                    port:
                      type: integer
                    protocol:
                      type: string
                    sessionLayer:
                      type: string
                    presentationLayer:
                      type: string
                    applicationLayer:
                      type: string
                    authenticated:
                      type: boolean
                      nullable: true

