apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificates.skupper.io
spec:
  group: skupper.io
  names:
    kind: Certificate
    plural: certificates
    singular: certificate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Identifies the CA to be used in signing the certificate
      jsonPath: .spec.ca
      name: CA
      type: string
    - description: Whether or not the certificate is valid for use as a server
      jsonPath: .spec.server
      name: Server
      type: boolean
    - description: Whether or not the certificate is valid for use as a client
      jsonPath: .spec.client
      name: Client
      type: boolean
    - description: Whether or not the certificate is valid for use as a CA
      jsonPath: .spec.signing
      name: Signing
      type: boolean
    - description: The status of the certificate
      jsonPath: .status.status
      name: Status
      type: string
    - description: The expiration of the certificate if relevant
      jsonPath: .status.expiration
      name: Expiration
      type: string
    - description: Any relevant human readable message
      jsonPath: .status.message
      name: Message
      type: string
    name: v2alpha1
    schema:
      openAPIV3Schema:
        description: An internal resource used to indicate TLS credentials to be created
        properties:
          spec:
            properties:
              ca:
                type: string
              client:
                type: boolean
              hosts:
                items:
                  type: string
                type: array
              server:
                type: boolean
              settings:
                additionalProperties:
                  type: string
                type: object
              signing:
                type: boolean
              subject:
                type: string
            required:
            - ca
            - subject
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              expiration:
                format: date-time
                type: string
              message:
                type: string
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
