apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bbbfrontends.b3scale.infra.run
spec:
  group: b3scale.infra.run
  names:
    kind: BBBFrontend
    listKind: BBBFrontendList
    plural: bbbfrontends
    singular: bbbfrontend
  scope: Namespaced

  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Desired state of the BBBFrontend resource.
              type: object
              properties:
                credentials:
                  description: Predefined credentials for the B3scale instance
                  type: object
                  nullable: true
                  properties:
                    key:
                      type: string
                      description: Predefined key for B3scale instance, will be defined if not set
                    secretRef:
                      description: SecretRef is a reference to a key in a Secret resource containing the key to connect to the BBB instance.
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        key:
                          description: The key of the entry in the Secret resource's `data` field to be used.
                          type: string
                        name:
                          description: 'Name of the resource being referred to. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                settings:
                  description: Settings defines the B3Scale instance settings
                  type: object
                  properties:
                    required_tags:
                      description: See https://github.com/b3scale/b3scale#middleware-configuration
                      type: array
                      nullable: true
                      items:
                        type: string
                    default_presentation:
                      type: object
                      nullable: true
                      description: See https://github.com/b3scale/b3scale#middleware-configuration
                      properties:
                        url:
                          type: string
                        force:
                          type: boolean
                    create_default_params:
                      type: object
                      nullable: true
                      description: See https://github.com/b3scale/b3scale#configure-create-parameter-defaults-and-overrides
                      additionalProperties:
                        type: string
                    create_override_params:
                      type: object
                      nullable: true
                      description: See https://github.com/b3scale/b3scale#configure-create-parameter-defaults-and-overrides
                      additionalProperties:
                        type: string
            status:
              description: Status of the BBBFrontend. This is set and managed automatically.
              type: object
              properties:
                conditions:
                  description: List of status conditions to indicate the status of the BBB frontend. Known condition types are `Ready`.
                  type: array
                  items:
                    description: BBBFrontendCondition contains condition information for an BBBFrontend.
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the timestamp corresponding to the last status change of this condition.
                        type: string
                        format: date-time
                      message:
                        description: Message is a human readable description of the details of the last transition, complementing reason.
                        type: string
                      observedGeneration:
                        description: If set, this represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.condition[x].observedGeneration is 9, the condition is out of date with respect to the current state of the BBBFrontend.
                        type: integer
                        format: int64
                      reason:
                        description: Reason is a brief machine readable explanation for the condition's last transition.
                        type: string
                      status:
                        description: Status of the condition, one of (`True`, `False`, `Unknown`).
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                      type:
                        description: Type of the condition, known values are (`Ready`).
                        type: string

