apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accounts.jetstream.nats.io
spec:
  group: jetstream.nats.io
  scope: Namespaced
  names:
    kind: Account
    singular: account
    plural: accounts
  versions:
  - name: v1beta2
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                description: A unique name for the Account.
                type: string
                pattern: '^[^.*>]*$'
                minLength: 1
              creds:
                description: The creds to be used to connect to the NATS Service.
                type: object
                properties:
                  secret:
                    type: object
                    properties:
                      name:
                        description: Name of the secret with the creds.
                        type: string
                  file:
                    description: Credentials file, generated with github.com/nats-io/nsc tool.
                    type: string
              servers:
                description: A list of servers to connect.
                type: array
                minLength: 1
                items:
                  type: string
                  minLength: 1
              tls:
                description: The TLS certs to be used to connect to the NATS Service.
                type: object
                properties:
                  secret:
                    type: object
                    properties:
                      name:
                        description: Name of the TLS secret with the certs.
                        type: string
                  ca:
                    description: Filename of the Root CA of the TLS cert.
                    type: string
                  cert:
                    description: Filename of the TLS cert.
                    type: string
                  key:
                    description: Filename of the TLS cert key.
                    type: string
              token:
                description: The token to be used to connect to the NATS Service.
                type: object
                properties:
                  secret:
                    type: object
                    properties:
                      name:
                        description: Name of the secret with the token.
                        type: string
                  token:
                    description: Key in the secret that contains the token.
                    type: string
              user:
                description: The user and password to be used to connect to the NATS Service.
                type: object
                properties:
                  secret:
                    type: object
                    properties:
                      name:
                        description: Name of the secret with the user and password.
                        type: string
                  user:
                    description: Key in the secret that contains the user.
                    type: string
                  password:
                    description: Key in the secret that contains the password.
                    type: string
              tlsFirst:
                description: When true, the KV Store will initiate TLS before server INFO.
                type: boolean
                default: false
          status:
            type: object
            properties:
              observedGeneration:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
