apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keyvalues.jetstream.nats.io
spec:
  group: jetstream.nats.io
  scope: Namespaced
  names:
    kind: KeyValue
    singular: keyvalue
    plural: keyvalues
    shortNames:
    - kv
  versions:
  - name: v1beta2
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              bucket:
                description: A unique name for the KV Store.
                type: string
              description:
                description: The description of the KV Store.
                type: string
              maxValueSize:
                description: The maximum size of a value in bytes.
                type: integer
              history:
                description: The number of historical values to keep per key.
                type: integer
              ttl:
                description: The time expiry for keys.
                type: string
              maxBytes:
                description: The maximum size of the KV Store in bytes.
                type: integer
              storage:
                description: The storage backend to use for the KV Store.
                type: string
                enum:
                - file
                - memory
              replicas:
                description: The number of replicas to keep for the KV Store in clustered JetStream.
                type: integer
                minimum: 1
                maximum: 5
                default: 1
              placement:
                description: The KV Store placement via tags or cluster name.
                type: object
                properties:
                  cluster:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
              republish:
                description: Republish configuration for the KV Store.
                type: object
                properties:
                  destination:
                    type: string
                    description: Messages will be additionally published to this subject after Bucket.
                  source:
                    type: string
                    description: Messages will be published from this subject to the destination subject.
              mirror:
                description: A KV Store mirror.
                type: object
                properties:
                  name:
                    type: string
                  optStartSeq:
                    type: integer
                  optStartTime:
                    description: Time format must be RFC3339.
                    type: string
                  filterSubject:
                    type: string
                  externalApiPrefix:
                    type: string
                  externalDeliverPrefix:
                    type: string
                  subjectTransforms:
                    description: List of subject transforms for this mirror.
                    type: array
                    items:
                      description: A subject transform pair.
                      type: object
                      properties:
                        source:
                          description: Source subject.
                          type: string
                        dest:
                          description: Destination subject.
                          type: string
              compression:
                description: KV Store compression.
                type: boolean
              sources:
                description: A KV Store's sources.
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    optStartSeq:
                      type: integer
                    optStartTime:
                      description: Time format must be RFC3339.
                      type: string
                    filterSubject:
                      type: string
                    externalApiPrefix:
                      type: string
                    externalDeliverPrefix:
                      type: string
                    subjectTransforms:
                      description: List of subject transforms for this mirror.
                      type: array
                      items:
                        description: A subject transform pair.
                        type: object
                        properties:
                          source:
                            description: Source subject.
                            type: string
                          dest:
                            description: Destination subject.
                            type: string
              account:
                description: Name of the account to which the Stream belongs.
                type: string
                pattern: '^[^.*>]*$'
              creds:
                description: NATS user credentials for connecting to servers. Please make sure your controller has mounted the creds on its path.
                type: string
                default: ''
              nkey:
                description: NATS user NKey for connecting to servers.
                type: string
                default: ''
              preventDelete:
                description: When true, the managed KV Store will not be deleted when the resource is deleted.
                type: boolean
                default: false
              preventUpdate:
                description: When true, the managed KV Store will not be updated when the resource is updated.
                type: boolean
                default: false
              servers:
                description: A list of servers for creating the KV Store.
                type: array
                items:
                  type: string
                default: []
              tls:
                description: A client's TLS certs and keys.
                type: object
                properties:
                  clientCert:
                    description: A client's cert filepath. Should be mounted.
                    type: string
                  clientKey:
                    description: A client's key filepath. Should be mounted.
                    type: string
                  rootCas:
                    description: A list of filepaths to CAs. Should be mounted.
                    type: array
                    items:
                      type: string
              tlsFirst:
                description: When true, the KV Store will initiate TLS before server INFO.
                type: boolean
                default: false
              jsDomain:
                description: The JetStream domain to use for the KV store.
                type: string
          status:
            type: object
            properties:
              observedGeneration:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
    additionalPrinterColumns:
    - name: State
      type: string
      description: The current state of the KV Store.
      jsonPath: .status.conditions[?(@.type == 'Ready')].reason
    - name: KV Store Name
      type: string
      description: The name of the KV Store.
      jsonPath: .spec.bucket
