name: Update Migration Status

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-migration-status.yaml
      - schema
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-migrations-status:
    name: Update Migration Status
    runs-on: ubuntu-latest
    if: github.repository == 'CustomResourceDefinition/catalog' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY_SCHEDULED_JOBS }}

      - uses: actions/checkout@v4
        with:
          repository: datreeio/CRDs-catalog
          path: build/remote/datreeio

      - run: make generate-status

      - uses: EndBug/add-and-commit@v9
        name: Publish changes
        if: github.repository == 'CustomResourceDefinition/catalog' && github.ref == 'refs/heads/main'
        with:
          add: MIGRATION.md
          default_author: github_actions
