apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterpolicyviolations.kyverno.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.policy
    description: The policy that resulted in the violation
    name: Policy
    type: string
  - JSONPath: .spec.resource.kind
    description: The resource kind that cause the violation
    name: ResourceKind
    type: string
  - JSONPath: .spec.resource.name
    description: The resource name that caused the violation
    name: ResourceName
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: kyverno.io
  names:
    kind: ClusterPolicyViolation
    plural: clusterpolicyviolations
    shortNames:
    - cpolv
    singular: clusterpolicyviolation
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            policy:
              type: string
            resource:
              properties:
                kind:
                  type: string
                name:
                  type: string
              required:
              - kind
              - name
              type: object
            rules:
              items:
                properties:
                  message:
                    type: string
                  name:
                    type: string
                  type:
                    type: string
                required:
                - name
                - type
                - message
                type: object
              type: array
          required:
          - policy
          - resource
          - rules
  versions:
  - name: v1
    served: true
    storage: true
